server:
    port: 8102
spring:
    cloud:
        consul:
            discovery:
                instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
                ip-address: true
            host: localhost
            port: 8500
    sleuth:
        sampler:
            percentage: 1.0
    zipkin:
        base-url: http://localhost:9411    