server:
    port: 8400
spring:
    sleuth:
        sampler:
            percentage: 1.0
    zipkin:
        base-url: http://localhost:9411
zuul:
    routes:
        fs-consumer: /consumer/**
        fs-provider: /provider/**
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 80000        